title: JAKE9WI
url: "https://jake9wi.github.io"
baseurl: ""  # no trailing slash
future: true

collections:
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  ares:
    output: true
    permalink: /ares/:year/:month/:day/:title/
