---
title: JAKE9WI
url: "https://jake9wi.github.io"  # or your custom domain
future: true
collections:
  blog:
    output: true
    permalink: /blog/:title/
  ares:
    output: true
    permalink: /ares/:title/

---
